collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7795699
  brandStrength: 0.8369176
  lightness: 0.2150538
  brandColors:
    - '#1A1D24'
    - '#6A6A76'
    - '#A5A3AE'
    - '#FFFFF2'
    - '#FFBD6A'
  rhythmicContrast: 0.3100359
typography_spectrum: 0.327957
layout_spectrum: 1
name: pniyomsilp
